### PR TITLE
make evmLog contract address case insensitive

### PR DESCRIPTION
**Pull request by belopash**

### CODE REVIEW

**Review by eldargab — CHANGES_REQUESTED** [review]
Hey, address normalisation should be done at `.addEvmLogHandler()` and `.addEvmLog()`
level. Otherwise, handler based processor will not work.

**Comment by belopash** [comment]
@eldargab should we do the same with contract addresses for `.addContractsContractEmittedHandler()` and `addContractsContractEmitted()`?

**Comment by eldargab** [comment]
> should we do the same with contract addresses for `.addContractsContractEmittedHandler()` and `addContractsContractEmitted()`?

You mean`.toLowerCase()`? Seems like we should.

**Comment by eldargab** [comment]
Hey, @RaekwonIII and @dzhelezov  !

For batch processing the above normalisation will not help, because an explicit dispatch on a contract address will be often required.

```ts
if (item.event.args.contract == '0xaA...') {
else {
}
```

Docs should clearly advise to work only with decoded raw addresses in a lower cased hex form.

**Pull request merged**
